[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 10

[fmt]
tab_width = 2

[profile.ci]
optimizer = true
optimizer_runs = 10

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
